### ISSUE TITLE
Frankfurt, Germany not found

### ISSUE THREAD

**Issue by justmarkup** [justmarkup/iss-observer.com#2]
When searching for Frankfurt it shows no result at the moment. Problem is probably because there are two Frankfurt in Germany where we have data.

**Comment by machtweb** [comment]
let the user decide

**Comment by justmarkup** [comment]
Solved this by adding a datalist with all available cities, so once user starts writing down the location they can choose one of the available options - in case of Frankfurt there is Frankfurt_am_Main and Frankfurt_an_der_Oder.

@machtweb Does this work for you or would you prefer another solution?
