### ISSUE TITLE
morning/evening checkbox labels

### ISSUE THREAD

**Issue by VladPoe** [justmarkup/iss-observer.com#3]
evening checkbox label has "morning" value for 'for' attribute

` <label for="morning">
              <input type="checkbox" checked="" id="evening" value="evening">
              evening
   </label>`

**Comment by justmarkup** [comment]
Hi @VladPoe 

Thanks a lot for reporting this issue. A fix just made it to production with version 1.2.0

**Comment by VladPoe** [comment]
hi @justmarkup !
thank you for the articles and push-notification explanations
